### ISSUE TITLE
Is it Possible to add Authentication to the API

### ISSUE THREAD

**Issue by satish860** [hallatore/Netling#13]
I was trying the tool, It is pretty cool !! I am trying to understanding How to add Windows authentication process into the request

**Comment by hallatore** [comment]
Some of this will be solved by adding support for headers #9 as you can add auth headers, etc.
But I'm not sure if that's enough to support windows auth as it's normally some handshake going back and forth.

So the question is, can you get authentication to work by only adding some request headers?

**Comment by satish860** [comment]
I will try it by just adding header .. Or Is it possible to call a request with a Windows  authentication and add the header to HTTP worker

**Comment by hallatore** [comment]
I've added support for headers now. Hope that helps if you haven't already added this support yourself :)

I won't be supporting much outside the standard http stuff, but people are welcome to fork and tweak to their liking. :)

**Comment by satish860** [comment]
Thanks @hallatore . Awesome product. I will be doing a blog post on this.
