### ISSUE TITLE
ensure text is visible for those with red-green color blindness

### ISSUE THREAD

**Issue by shanselman** [hallatore/Netling#15]

**Comment by hallatore** [comment]
Right now it's just Red and Green, I think it's ok if both look equal as long as they are still readable.

@shanselman Any online tests I can use to ensure this?

**Comment by chezuma** [comment]
http://littlebigdetails.com/post/35775193711/trello-color-blind-friendly-mode-makes

This did wonders for me when using Trello! Yes, I am red/green colorblind.

**Comment by hallatore** [comment]
@chezuma How is your experience using Netling? Are the red/green values the same? And any input on what you would do to fix it?

**Comment by chezuma** [comment]
Unfortunately for me, they are easily mixed. The red ones doesn't stand out. Using blues instead of greens is always a neat trick, makes it a lot easier.

**Comment by jnm2** [comment]
I think red/green is the most compelling visual, so I'd want that to be default and colorblind mode could be opted in.

**Comment by SecretDeveloper** [comment]
How about including a non colour element to also indicate success/improvement.  Something like a Tick icon or Up/Down arrows?

**Comment by ChristopherGLewis** [comment]
I've got a pretty simple hash background for the ValueUserControl that solves this here: 
https://github.com/ChristopherGLewis/Netling

![image](https://cloud.githubusercontent.com/assets/8505994/17568663/4e4d4e24-5f0a-11e6-8de2-0b9af9aeefd4.png)

**Comment by hallatore** [comment]
Nice. I will check it out.

But I won't implement it as an option. The default implementation has to work for all.

**Comment by ChristopherGLewis** [comment]
Its actually just a small change to the ValueUserControl to toggle a background VisualBrush.  Its a new property (UseADA) that defaults to false.  When set to true, it sets the VisualBrush background to visible.  

I added a checkbox to the ResultWindow that toggles the ValueUserControl.UseADA value for all the items.

**Comment by BNDKPNTR** [comment]
Hi, I also created a version where you can change between red-green and red-blue colors, and the selected option is saved so you dont have to change it at every startup.

https://github.com/BNDKPNTR/Netling

<img width="477" alt="capture" src="https://cloud.githubusercontent.com/assets/8028884/17570212/cde6360a-5f4b-11e6-9b0c-c88dcf15963f.PNG">

**Comment by hallatore** [comment]
Here is my test so far. Is this enough or easy to miss? 
![](http://i.imgur.com/SZtXL4Z.png)

**Comment by chezuma** [comment]
The blue/red one is awesome for me, but the red striped one works just as good. 

Now its just a matter of taste :) great work to both of you, make them each an option :D 

The one with the grid in the background was just to noisy for my eyes anyways.

**Comment by hallatore** [comment]
I've added the one from the screenshot above. It should work well enough while still following the theme I have for the app. 

PS: Let me know if it still needs tweaking. :)

**Comment by ChristopherGLewis** [comment]
Looks great - My only suggestion would be to move the VisualBrush to the UserControl to better allow the control to be reused.
