### ISSUE TITLE
ByteHelpers.ContainsPossibly for byte looks wrong

### ISSUE THREAD

**Issue by nietras** [hallatore/Netling#16]
@hallatore  fixed `bufferPtr` is not used nor is `value` used in this overload see:

https://github.com/hallatore/Netling/blob/master/Netling.Core/Utils/ByteHelpers.cs#L26

**Comment by hallatore** [comment]
The byte pointer is redundant and a result of copy from the original method. `value` is used however.

**Comment by nietras** [comment]
Ah yes, sorry I missed the `value`, would not have made sense without it. One question, is this the only place you use `Unsafe` or have you used it in other places?

**Comment by hallatore** [comment]
I only use it here because I create a `Vector<short>` from a byte array.
Proper way to do it is to create a `Vector<byte>` from the array and then cast it, but that is too slow :)
