### ISSUE TITLE
Request for Chocolatey package

### ISSUE THREAD

**Issue by jnm2** [hallatore/Netling#18]
I would love to be able to [`choco install netling`](https://chocolatey.org/packages?q=netling) and be up in running in seconds on any computer, and I think a lot of other folks would agree.

Publishing an app to Chocolatey is the moral equivalent of publishing a library to NuGet and it can be automated on build servers.

**Comment by jnm2** [comment]
@hallatore Is see this issue has just been closed. Is this something you don't plan to provide?

**Comment by jnm2** [comment]
@hallatore I see this issue has just been closed. Is this something you don't plan to provide?

**Comment by hallatore** [comment]
I don't use Chocolatey myself, so I'm not planning on adding that. For now.

PS: I've added some pre-build binaries under Release.
