### ISSUE TITLE
Expose custom headers in UI

### ISSUE THREAD

**Issue by Huachao** [hallatore/Netling#19]
Can we have some place to set the custom headers in the UI?

**Comment by simonmurdock** [comment]
This would be good, I currently require this to pass "accept" headers - allowing me to compare protobuf serialization to json

**Comment by jstallm** [comment]
Its pretty straightforward to add headers in source code if your willing to clone the repo and write the code yourself. Adding in the UI doesnt seem as strait forward since the passing of the headers from UI layer down through the method signatures means a lot of updates. Just try it in code.

**Comment by jstallm** [comment]
@hallatore , do you think this issue can be closed since it was stated that this type of update be done on a individual clone basis only in the readme?

> Need custom headers, data, etc? Fork and tweak it to your needs! :)

**Comment by hallatore** [comment]
Fork and tweak it is the way to go! :)

I might add some features like this in the future. But I want the base app to be as small as possible. So I'm trying to have as few features as possible.
