### ISSUE TITLE
Downloadable binaries

### ISSUE THREAD

**Issue by manikantag** [hallatore/Netling#20]
Hi, Netling looks very clean & modern. But I can't try it out as I m not into .Net world :) Can you release downloadable (if possible, portable) binary file? Thanks.

**Comment by moser96** [comment]
I would like an easy fast one click installer. I can highly recommend https://github.com/Squirrel/Squirrel.Windows

**Comment by fxlv** [comment]
Or perhaps some build instructions for absolute n00bs would be great too.

**Comment by fxlv** [comment]
Ok, turns out that building is as simple as opening the solution in the Visual Studio and running the build.

**Comment by hallatore** [comment]
I haven't really made any binaries because it is really easy to build. And that I want people to tweak it to their needs. It's also a very experimental project.

**Comment by hallatore** [comment]
Added zipped binaries to Release page.
