### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by vkocjancic** [hallatore/Netling#21]
Hi. I love your application.

I am missing authentication options though. Working on client based applications, majority of pages are protected by either username & password combination or Windows authentication.

Is there a plan to implement this?

**Comment by HalidCisse** [comment]
+1 for OAuth2 token header support

**Comment by hallatore** [comment]
I think the first step is to support custom headers in the client with #19. Then it would be easier to use already authenticated headers/cookies from chrome for example.
