### ISSUE TITLE
Need to add AllowUnsafeBlocks=true on Netling.Core for it to compile on xbuild

### ISSUE THREAD

**Issue by stanislavromanov** [hallatore/Netling#22]
Currently xbuild cannot compile the console version for it to run on mac or linux becasue it depends on `Core` which is doing some unsafe byte operations. We need to add the code below to `.csproj` file in `Core` library to fix this.
### Error

```
Utils/ByteHelpers.cs(8,23): error CS0227: Unsafe code requires the `unsafe' command line option to be specified
```
### Fix

Add line below in `.csproj` file of `Code` sub-project.

```
<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
```

**Comment by hallatore** [comment]
Can you make a pull request for this?

**Comment by stanislavromanov** [comment]
Yeah, OK.
