### ISSUE TITLE
Support Enable/Disable GZIP Compression

### ISSUE THREAD

**Issue by RehanSaeed** [hallatore/Netling#23]
I'm adding request decompression to my API (as opposed to the more common response compression) and would like to load test with GZIP'ed requests. Any chance of a simple check box or perhaps a combo-box (You may want to support other compression methods such as Deflate or Brotli) containing this option?

**Comment by hallatore** [comment]
Just fork the repo and add it yourself. There is header support, so it should be quite trivial to add the needed changes for your project.
