### ISSUE TITLE
Explain what pipelining means

### ISSUE THREAD

**Issue by Dissimilis** [hallatore/Netling#25]
Please explain in readme.md what pipelining parameter does.  It can be very confusing to understand without digging into source code.

**Comment by alasvant** [comment]
Was wondering the same and google gave this review of Netling: https://www.jeremymorgan.com/tutorials/linux/how-to-load-test-iis-web-server/

Copy paste from the page: "It has a feature for “Pipelining”. This is when multiple requests go through a single socket without waiting for a response. Setting this higher will generate a higher load but again this something to adjust for best results. There will be a physical limit to pipelining depending on your hardware and connection speed."

**Comment by hallatore** [comment]
Removed pipelining as it made the code very hard to tweak and error prone. It's a nice feature, but most don't need it for normal testing.

If they do, then wrk is a great linux app that supports it. Can use it with Bash for Windows.
Or copy back the old pipelining code from an earlier commit. :)
