### ISSUE TITLE
Suitability for unit tests

### ISSUE THREAD

**Issue by brentarias** [hallatore/Netling#28]
I'd like to expand your tool so that it can also run unit tests through a load-test scenario.

A full explanation of what I want is in this [SO post](https://stackoverflow.com/questions/51408770/load-stress-test-with-unit-test-paradigm).

How readily do you think your code could be adjusted for this?

**Comment by hallatore** [comment]
Something like this might be a good starting point.

```
Worker worker = new Worker(new SocketWorkerJob(uri));
WorkerResult result = await worker.Run(count.Value, new CancellationToken());
// Do something with the result ...
```
