### ISSUE TITLE
Are you accepting pull requests?

### ISSUE THREAD

**Issue by bunceg** [hallatore/Netling#29]
I've made a few custom changes to Netling to accept different HTTP methods, authentication tokens etc. via the console app but I've not done this via the WPF because (a) I don't use it and (b) I don't really do any WPF development.

If I created a pull request would you integrate them into the master branch or are you not really interested in handling these kinds of additional features (additional work for you to manage etc)?

**Comment by ErikSchierboom** [comment]
@hallatore I'm also interested in if you accept PR's.

**Comment by hallatore** [comment]
Hey!

It's been a bit slow here in the anticipation of .NET Core 3.0 and stuff like span/memory.

I'm not really accepting new features as I want to keep the initial version as clean/small as possible. Still want to rewrite part of the app. Maybe test out pipelines.
