### ISSUE TITLE
Download of exe

### ISSUE THREAD

**Issue by AshleyDhevalall** [hallatore/Netling#32]
Hi there,

Would it please be possible to provide a direct link to the .exe download

Looking for a .net framework version

Kind Regards
Ash D

**Comment by wonea** [comment]
.NET Framework is being replaced by .NET Core, I suspect it might be problematic to back port it .NET Framework if C# 8.0  features are used.

**Comment by hallatore** [comment]
If you download the code before the .net core migration it works on .NET 4.7.1

https://github.com/hallatore/Netling/tree/edc7470defc597b3ee63f1b608d7f200cb33442c
