### ISSUE TITLE
How to test post request from WPF client

### ISSUE THREAD

**Issue by VenkateshSrini** [hallatore/Netling#39]
Hi,
Is there a way by which I can test the post and put request using NetLing. If so please let me know.

**Comment by hallatore** [comment]
You can edit the default message and compile. Or extend it and add extra stuff to it.

If you look at HttpWorker it already takes method as an argument. https://github.com/hallatore/Netling/blob/master/Netling.Core.SocketWorker/Performance/HttpWorker.cs#L15
