### ISSUE TITLE
Refactor code so it also can support a console application

### ISSUE THREAD

**Issue by hallatore** [hallatore/Netling#8]
Refactor the core logic back into Netling.Core in such a way that it's easier to support multiple types of apps. Netling.Core should be usable on it's own for third party libs.

**Comment by killnine** [comment]
What in particular isn't exposed very well in the core? Or, rather, what is the UI doing that it shouldn't be?

**Comment by hallatore** [comment]
The processing of the result is somewhat all over the place at the moment. Too much is done in the ResultWindow.

I'm almost done with this btw. The new entry point will look like this and do the work async.

```
var result = await Netling.Core.Worker.Run(url, threads, ...);
```
